### PR TITLE
List All Shows Added

### PR DESCRIPTION
**Pull request by mkeshavgarg**

### CODE REVIEW

**Comment by pdoongarwal** [comment]
@mkeshavgarg Please read CONTRIBUTING.md, do not send PR to master branch.
Describe the work you have done, it will be helpful if before sending a PR you can notify us by making an issue regarding it.

**Comment by mkeshavgarg** [comment]
@pdoongarwal Thanks, I will close this and log an issue

**Comment by MayankPratap** [comment]
Hey @mkeshavgarg,  I have changed the files in our dev branch to list all available shows and added you as a contributor in CONTRIBUTORS.md file. 

If you are interested in adding something to this repo, you are most welcome. Currently we are using 
http://tvshows4mobile.com to download mp4 videos. We are planning to use http://dayt.se/ to download episodes in HD Quality. You are free to implement the same working of downloader for HD Videos. 

Please send PRs to dev branch of this repository.

**Comment by mkeshavgarg** [comment]
Hey, @MayankPratap, Great that all changes have been successfully merged. 
I will implement the same for HD videos downloader and will surely send PRs to dev branch.

**Pull request closed without merging**
